#pragma config(Sensor, dgtl11, shaftencoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftlift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftlift2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightlift2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightlift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[right] = (vexRT[Ch2]);
		motor[right2] = (vexRT[Ch2]);
		motor[left] = (vexRT[Ch3]);
		motor[left2] = (vexRT[Ch3]);

		if (vexRT[Btn7D] == 1)             //first autonomus
		{
			motor[arm]=120;
			motor[arm2]=120;
			motor[right]=127;
			motor[left]=127;
			motor[right2]=127;
			motor[left2]=127;


			wait1Msec(700);
			stopAllMotors();

			SensorValue[shaftencoder] = 0;

			while(SensorValue[shaftencoder] < 78)
			{
				motor[leftlift]=120;
				motor[rightlift]=120;
				motor[leftlift2]=120;
				motor[rightlift2]=120;
			}
			stopAllMotors();
			motor[right]=127;
			motor[left]=127;
			motor[right2]=127;
			motor[left2]=127;
			wait1Msec(1500);
			stopAllMotors();


			motor[right]=-127;
			motor[left]=-127;
			motor[right2]=-127;
			motor[left2]=-127;
			wait1Msec(900);
			stopAllMotors();



			motor[right]=127;
			motor[left]=-127;
			motor[right2]=127;
			motor[left2]=-127;
			wait1Msec(800);
			stopAllMotors();


			motor[leftlift]=-120;
			motor[rightlift]=-120;
			motor[leftlift2]=-120;
			motor[rightlift2]=-120;
			wait1Msec(1200);
			stopAllMotors();



			motor[right]=127;
			motor[left]=127;
			motor[right2]=127;
			motor[left2]=127;
			wait1Msec(900);
			stopAllMotors();



			motor[arm]=120;
			motor[arm2]=120;
			wait1Msec(1700);
			stopAllMotors();

			motor[leftlift]=120;
			motor[rightlift]=120;
			motor[leftlift2]=120;
			motor[rightlift2]=120;
			motor[arm]=100;
			motor[arm2]=100;
			motor[right]=-120;
			motor[left]=120;
			motor[right2]=-120;
			motor[left2]=120;
			wait1Msec(1600);
			stopAllMotors();



			motor[leftlift]=120;
			motor[rightlift]=120;
			motor[leftlift2]=120;
			motor[rightlift2]=120;
			wait1Msec(400);
			stopAllMotors();
			motor[leftlift]=120;
			motor[rightlift]=120;
			motor[leftlift2]=120;
			motor[rightlift2]=120;
			motor[arm]=60;
			motor[arm2]=60;
			wait1Msec(650);
			stopAllMotors();
			motor[right]=127;
			motor[left]=127;
			motor[right2]=127;
			motor[left2]=127;
			wait1Msec(1250);
			stopAllMotors();


			motor[arm]=-120;
			motor[arm2]=-120;
			wait1Msec(700);
			stopAllMotors();
			motor[right]=-127;
			motor[left]=-127;
			motor[right2]=-127;
			motor[left2]=-127;
			wait1Msec(1000);
			stopAllMotors();
		}


		if (vexRT[Btn8D] == 1)             //first autonomus left side
		{
			motor[arm]=120;
			motor[arm2]=120;
			motor[right]=127;
			motor[left]=127;
			motor[right2]=127;
			motor[left2]=127;


			wait1Msec(700);
			stopAllMotors();

			SensorValue[shaftencoder] = 0;

			while(SensorValue[shaftencoder] < 78)
			{
				motor[leftlift]=120;
				motor[rightlift]=120;
				motor[leftlift2]=120;
				motor[rightlift2]=120;
			}
			stopAllMotors();
			motor[right]=127;
			motor[left]=127;
			motor[right2]=127;
			motor[left2]=127;
			wait1Msec(1500);
			stopAllMotors();


			motor[right]=-127;
			motor[left]=-127;
			motor[right2]=-127;
			motor[left2]=-127;
			wait1Msec(900);
			stopAllMotors();



			motor[right]=-127;
			motor[left]=127;
			motor[right2]=-127;
			motor[left2]=127;
			wait1Msec(800);
			stopAllMotors();


			motor[leftlift]=-120;
			motor[rightlift]=-120;
			motor[leftlift2]=-120;
			motor[rightlift2]=-120;
			wait1Msec(1200);
			stopAllMotors();



			motor[right]=127;
			motor[left]=127;
			motor[right2]=127;
			motor[left2]=127;
			wait1Msec(900);
			stopAllMotors();



			motor[arm]=120;
			motor[arm2]=120;
			wait1Msec(1700);
			stopAllMotors();

			motor[leftlift]=120;
			motor[rightlift]=120;
			motor[leftlift2]=120;
			motor[rightlift2]=120;
			motor[arm]=100;
			motor[arm2]=100;
			motor[right]=120;
			motor[left]=-120;
			motor[right2]=120;
			motor[left2]=-120;
			wait1Msec(1600);
			stopAllMotors();



			motor[leftlift]=120;
			motor[rightlift]=120;
			motor[leftlift2]=120;
			motor[rightlift2]=120;
			wait1Msec(400);
			stopAllMotors();
			motor[leftlift]=120;
			motor[rightlift]=120;
			motor[leftlift2]=120;
			motor[rightlift2]=120;
			motor[arm]=60;
			motor[arm2]=60;
			wait1Msec(650);
			stopAllMotors();
			motor[right]=127;
			motor[left]=127;
			motor[right2]=127;
			motor[left2]=127;
			wait1Msec(1250);
			stopAllMotors();


			motor[arm]=-120;
			motor[arm2]=-120;
			wait1Msec(700);
			stopAllMotors();
			motor[right]=-127;
			motor[left]=-127;
			motor[right2]=-127;
			motor[left2]=-127;
			wait1Msec(1000);
			stopAllMotors();
		}




		if (vexRT[Btn7R])         //counter-strategy
		{
			motor[arm] = 30;
			motor[arm2] = 30;
			wait1Msec(400);
			motor[arm] = 0;
			motor[arm] = 0;

			wait1Msec(1600);

			motor[right] = 127;
			motor[left] = 75;
			motor[right2] = 127;
			motor[left2] = 75;   //opens his hands and pushes the stars underneath
			motor[arm] = 17;
			motor[arm2] = 17;
			wait1Msec(3000);
			motor[right] = 0;
			motor[left] = 0;
			motor[right2] = 0;
			motor[left2] =0;
			motor[arm] = 0;
			motor[arm2] = 0;

			motor[right] = -127;
			motor[left] = -127; //goes back a bit
			motor[right2] = -127;
			motor[left2] = -127;
			motor[arm] = -20;
			motor[arm2] = -20;
			wait1Msec(900);

			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = -127;
			motor[left2] = -127;  //turns left (4 the pillow)
			wait1Msec(550);
			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = 127;
			motor[left2] = 127;
			wait1Msec(550);

			motor[arm] = 127;
			motor[arm2] = 127;
			wait1Msec(1200);
			motor[rightlift] = 110;
			motor[rightlift2] = 110;
			motor[leftlift] = 110;
			motor[leftlift2] = 110;
			motor[arm] = 70;
			motor[arm2] = 70;
			motor[right] = -40;
			motor[right2] = -40;
			motor[left] = 40;
			motor[left2] = 40;
			wait1Msec(2000);

			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = 127;
			motor[left2] = 127;
			wait1Msec(1800);
			motor[arm] = -127;
			motor[arm2] = -127;
			wait1Msec(900);

			motor[arm] = 0;
			motor[arm2] = 0;
			motor[right] = -127;
			motor[right2] = -127;
			motor[left] = -127;
			motor[left2] = -127;
			wait1Msec(500);
			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = 127;
			motor[left2] = 127;
			wait1Msec(700);
			motor[right] = -127;
			motor[right2] = -127;
			motor[left] = -127;
			motor[left2] = -127;
			wait1Msec(1000);
			motor[right] = 0;
			motor[right2] = 0;
			motor[left] = 0;
			motor[left2] = 0;

		}

		if (vexRT[Btn8L] == 1)  // counter-strategy left side
		{
			motor[arm] = 30;
			motor[arm2] = 30;
			wait1Msec(400);
			motor[arm] = 0;
			motor[arm] = 0;

			wait1Msec(1600);

			motor[right] = 127;
			motor[left] = 70;
			motor[right2] = 127;
			motor[left2] = 70; //ens his hands and pushes the stars underneath
			motor[arm] = 17;
			motor[arm2] = 17;
			wait1Msec(3000);
			motor[right] = 0;
			motor[left] = 0;
			motor[right2] = 0;
			motor[left2] =0;
			motor[arm] = 0;
			motor[arm2] = 0;

			motor[right] = -127;
			motor[left] = -127; //goes back a bit
			motor[right2] = -127;
			motor[left2] = -127;
			motor[arm] = -20;
			motor[arm2] = -20;
			wait1Msec(900);

			motor[right] = -127;
			motor[right2] = -127;
			motor[left] = 127;
			motor[left2] = 127;  //turns right (4 the pillow)
			wait1Msec(550);
			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = 127;
			motor[left2] = 127;
			wait1Msec(550);

			motor[arm] = 127;
			motor[arm2] = 127;
			wait1Msec(1200);
			motor[rightlift] = 110;
			motor[rightlift2] = 110;
			motor[leftlift] = 110;
			motor[leftlift2] = 110;
			motor[arm] = 70;
			motor[arm2] = 70;
			motor[right] = 40;
			motor[right2] = 40;
			motor[left] = -40;
			motor[left2] = -40;
			wait1Msec(2000);

			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = 127;
			motor[left2] = 127;
			wait1Msec(1800);
			motor[arm] = -127;
			motor[arm2] = -127;
			wait1Msec(900);

			motor[arm] = 0;
			motor[arm2] = 0;
			motor[right] = -127;
			motor[right2] = -127;
			motor[left] = -127;
			motor[left2] = -127;
			wait1Msec(500);
			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = 127;
			motor[left2] = 127;
			wait1Msec(700);
			motor[right] = -127;
			motor[right2] = -127;
			motor[left] = -127;
			motor[left2] = -127;
			wait1Msec(1000);
			motor[right] = 0;
			motor[right2] = 0;
			motor[left] = 0;
			motor[left2] = 0;

		}

		if (vexRT[Btn7U] == 1)    // third autonomus
		{
			motor[arm] = 127;
			motor[arm2] = 127;
			wait1Msec(950);
			motor[arm] = 0;
			motor[arm2] = 0;
			motor[right] = 127;
			motor[left] = -127;
			motor[right2] = 127;
			motor[left2] = -127;
			wait1Msec(1200);

			motor[right] = -127;
			motor[left] = -127;
			motor[right2] = -127;
			motor[left2] = -127;
			wait1Msec(900);
			motor[rightlift] = -7;
			motor[rightlift2] = -7;
			motor[leftlift] = -7;
			motor[leftlift2] = -7;
			motor[right] = 100;
			motor[left] = 127;
			motor[right2] = 100;
			motor[left2] = 127;
			wait1Msec(4000);

			motor[arm] = 127;
			motor[arm2] = 127;
			motor[right] = -127;
			motor[right2] = -127;
			motor[left] = 127;
			motor[left2] = 127;
			motor[rightlift] = 127;
			motor[rightlift2] = 127;
			motor[leftlift2] = 127;
			wait1Msec(600);
			stopAllMotors();

			/*

			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = 127;
			motor[left2] = 127;
			wait1Msec(600);
			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = 127;
			motor[left2] = 127;
			motor[rightlift] = 127;
			motor[rightlift2] = 127;
			motor[leftlift] = 127;
			motor[leftlift2] = 127;
			wait1Msec(1600);
			*/
		}


		if (vexRT[Btn8U] == 1)    // third autonomus left side
		{
			motor[arm] = 127;
			motor[arm2] = 127;
			wait1Msec(950);
			motor[arm] = 0;
			motor[arm2] = 0;
			motor[right] = -127;
			motor[left] = 127;
			motor[right2] = -127;
			motor[left2] = 127;
			wait1Msec(1200);

			motor[right] = -127;
			motor[left] = -127;
			motor[right2] = -127;
			motor[left2] = -127;
			wait1Msec(900);
			motor[rightlift] = -7;
			motor[rightlift2] = -7;
			motor[leftlift] = -7;
			motor[leftlift2] = -7;
			motor[right] = 100;
			motor[left] = 127;
			motor[right2] = 100;
			motor[left2] = 127;
			wait1Msec(4000);

			motor[arm] = 127;
			motor[arm2] = 127;
			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = -127;
			motor[left2] = -127;
			motor[rightlift] = 127;
			motor[rightlift2] = 127;
			motor[leftlift2] = 127;
			wait1Msec(600);
			stopAllMotors();

			/*

			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = 127;
			motor[left2] = 127;
			wait1Msec(600);
			motor[right] = 127;
			motor[right2] = 127;
			motor[left] = 127;
			motor[left2] = 127;
			motor[rightlift] = 127;
			motor[rightlift2] = 127;
			motor[leftlift] = 127;
			motor[leftlift2] = 127;
			wait1Msec(1600);
			*/
		}



		if (vexRT[Btn5U] == 1 && SensorValue[shaftencoder] < 78)
		{
			motor[rightlift] = 127;
			motor[rightlift2] = 127;
			motor[leftlift] = 127;
			motor[leftlift2] = 127;
		}
		else if (vexRT[Btn5D] == 1 && SensorValue[shaftencoder] > 0)
		{
			motor[rightlift] = -127;
			motor[rightlift2] = -127;
			motor[leftlift] = -127;
			motor[leftlift2] = -127;
		}
		else
		{
			motor[rightlift] = 0;
			motor[rightlift2] = 0;
			motor[leftlift] = 0;
			motor[leftlift2] = 0;
		}

		if (vexRT[Btn6U] == 1)
		{
			motor[arm] = 127;
			motor[arm2] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[arm] = -127;
			motor[arm2] = -127;
		}
		else
		{
			motor[arm] = 0;
			motor[arm2] = 0;
		}
	}
}
