#pragma config(Motor,  port1,           L_LIFT_1,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           L_LIFT_2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           R_LIFT_1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           R_LIFT_2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           WHEEL_L_1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           WHEEL_L_2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           WHEEL_R_1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           CLAW_R,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           CLAW_L,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          WHEEL_R_2,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		/* Wheels */

		//Get joystick values
		int joyY1 = vexRT[Ch3];
		int joyY2 = vexRT[Ch2];

		motor[port5] = joyY1;
		motor[port6] = joyY1;
		motor[port7] = joyY2;
		motor[port10] = joyY2;

		/* Control columns */
		if(vexRT[Btn5U] == 1) {
			//Go upwards
			motor[port1] = 127;
			motor[port2] = 127;
			motor[port3] = -127;
			motor[port4] = -127;
		}
		else if(vexRT[Btn5D] == 1) {
			//Go downwards
			motor[port1] = -127;
			motor[port2] = -127;
			motor[port3] = 127;
			motor[port4] = 127;
		}
		else {
			//Stay in place
			motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port4] = 0;
		}


		/* Control claw */

		if(vexRT[Btn6D] == 1) {
			motor[port8] = 127;
			motor[port9] = -127;
		}
		else if(vexRT[Btn6U] == 1) {
			//Close
			motor[port8] = -127;
			motor[port9] = 127;
		}
		else {
			//Keep as is
			motor[port8] = 0;
			motor[port9] = 0;
		}
	}
}
