#pragma config(Sensor, dgtl11, shaftencoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftlift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftlift2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightlift2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightlift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

inline void setWheelL(int to) {
	motor[port1] = to;
	motor[port4] = to;
}

inline void setWheelR(int to) {
	motor[port7] = to;
	motor[port10] = to;
}

void setLift(int to) {
	motor[port2] = to;
	motor[port3] = to;
	motor[port8] = to;
	motor[port9] = to;
}

void setClaw(int to) {
	motor[port5] = to;
	motor[port6] = to;
}
task main()
{

	setWheelL(127);

	wait1Msec(500); stopAllMotors();

	setWheelL(127);
	setWheelR(127);

	wait1Msec(500);

	setClaw(127);

	wait1Msec(800); stopAllMotors();

	setClaw(127);
	setWheelL(127);
	setWheelR(127);

	/*wait1Msec(800); stopAllMotors();

	setClaw(127);
	setLift(127);

	setWheelL(-127);
	setWheelR(127);

	wait1Msec(1200); stopAllMotors();

	setClaw(127);

	wait1Msec(900); stopAllMotors();


	setWheelL(127);
	setWheelR(127);
	setLift(127);

	wait1Msec(600);

	setClaw(-127);

	wait1Msec(450); stopAllMotors();

	setLift(-127);
	setWheelL(-127);
	setWheelR(127);

	stopAllMotors(); wait1Msec(850);

	/*setWheelL(127);
	setWheelR(127);

	stopAllMotors(); wait1Msec(850);

	setClaw(127);

	stopAllMotors(); wait1Msec(850);

	setWheelL(127);
	setWheelR(-127);
	setLift(127);

	stopAllMotors(); wait1Msec(850);

	setClaw(-127);

	stopAllMotors(); wait1Msec(850);

	setLift(-127);

	setWheelL(127);
	setWheelR(-127);

	stopAllMotors(); wait1Msec(850);

	setWheelL(127);
	setWheelR(127);

	stopAllMotors(); wait1Msec(850);

	setClaw(127);

	stopAllMotors(); wait1Msec(850);

	setWheelL(-127);
	setWheelR(127);

	setLift(127);

	stopAllMotors(); wait1Msec(850);

	setClaw(-127);

	stopAllMotors(); wait1Msec(850);

	setLift(-127);

	setWheelL(127);
	setWheelR(-127);

	stopAllMotors(); wait1Msec(850);

	setWheelL(127);
	setWheelR(127);

	stopAllMotors(); wait1Msec(850);

	setClaw(127);

	stopAllMotors(); wait1Msec(850);

	setWheelL(-127);
	setWheelR(127);

	setLift(127);

	stopAllMotors(); wait1Msec(850);

	setClaw(-127);

	stopAllMotors(); wait1Msec(850);

	setWheelL(-127);
	setWheelR(127);

	stopAllMotors(); wait1Msec(850);

	setWheelL(127);
	setWheelR(127);

	stopAllMotors(); wait1Msec(1200);

	setLift(120);

	stopAllMotors(); wait1Msec(400);

	setWheelL(127);
	setWheelR(127);

	stopAllMotors(); wait1Msec(1200);

	setLift(127);

	stopAllMotors(); wait1Msec(400);

	setWheelL(127);
	setWheelR(127);

	stopAllMotors(); wait1Msec(1200);

	setWheelL(127);
	setWheelR(-127);

	stopAllMotors(); wait1Msec(850);
	*/
}
