#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
#pragma config(Sensor, dgtl2,  shaftencoder,   sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftlift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftlift2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           left2,         tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port5,           arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           right2,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port8,           rightlift2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightlift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int R = 45;
void setLift(int to) {
	motor[port2] = to;
	motor[port3] = to;
	motor[port8] = to;
	motor[port9] = to;
}

void setWheels(int to, bool turn = false, int direction = 0) {
	if(turn) {
		if(direction == -1) {
			motor[port7] = to;
			motor[port10] = to;
			motor[port1] = -to;
			motor[port4] = -to;
		}
		else {
			motor[port1] = to;
			motor[port4] = to;
			motor[port7] = -to;
			motor[port10] = -to;
		}
	}
	else {
		motor[port1] = to;
		motor[port4] = to;
		motor[port7] = to;
		motor[port10] = to;
	}
}

task main()
{
	int currentLevel = 1;

	int desiredClawAngle = 0;
	int desiredLiftAngle = 0;
	int desiredRotationAngle = 0;

	int currentClawAngle = 0;
	int currentLiftAngle = 0;
	int currentRotationAngle = 0;

	int desiredMovementAmount = 0; //length in centimeters
	int desiredMovementDirection = 0; //1 - forward, -1 - backwards
	while(true) {
		bool defaultCase = false;
		switch(currentLevel)
		{
			case 1: desiredMovementAmount = 50; desiredMovementDirection = 1; break;
			case 2: desiredRotationAngle = 90; break;
			case 3: desiredMovementAmount = 50; desiredMovementDirection = 1; desiredClawAngle =90; break; // ?
			case 4: desiredClawAngle = 0; break;
			case 5: desiredRotationAngle = 0; break;
			case 6: desiredMovementAmount = 100; desiredMovementDirection = 1; desiredLiftAngle = 90; break; //?
			case 7: desiredClawAngle = 90; break;
			case 8: desiredClawAngle = 0; desiredLiftAngle = 0; desiredRotationAngle = -90; break;
			case 9: desiredClawAngle = 90; desiredMovementAmount = 100; desiredMovementDirection = 1; break;
			case 10: desiredClawAngle = 0; break;
			case 11: desiredLiftAngle = 90; desiredRotationAngle = 0; break;
			case 12: desiredClawAngle = 90; break;
			case 13: desiredRotationAngle = 90; break;
			case 14: desiredMovementAmount = 90; desiredMovementDirection = 1; break; //?
			case 15: desiredLiftAngle = 0; desiredMovementAmount = 90; desiredMovementDirection = 1; break; //?
			case 16: desiredRotationAngle = 0; desiredLiftAngle = 90; desiredClawAngle = 0; break;
			case 17: desiredClawAngle = 90;
			case 18: desiredRotationAngle = 90; desiredLiftAngle = 0; break;
			case 19: desiredMovementAmount = 90; desiredMovementDirection = 1; break; //?
			case 20: desiredLiftAngle = 90; desiredRotationAngle = 0; desiredClawAngle = 0; break;
			case 21: desiredClawAngle = 90; break;
			case 22: desiredRotationAngle = -90; break;
			case 23: desiredMovementAmount = 90; desiredMovementDirection = 1; break; //?
			case 24: desiredMovementAmount = 90; desiredMovementDirection = 1; desiredLiftAngle = 75; break; //?
			case 25: desiredMovementAmount = 90; desiredMovementDirection = 1; desiredLiftAngle = 0; desiredClawAngle = 0; break;
			case 26: desiredRotationAngle = -180; desiredClawAngle = 90; break;
			case 27: desiredMovementAmount = 180; desiredMovementDirection = 1; desiredClawAngle = 90; break; //?
			case 28: desiredRotationAngle = -270; desiredClawAngle = 0; break;
			case 29: desiredMovementAmount = 180; desiredMovementDirection = 1; desiredClawAngle = 90; break;
			case 30: desiredClawAngle = 0; desiredRotationAngle = -360; break;
			case 31: desiredMovementAmount = 180; desiredMovementDirection = 1; desiredLiftAngle = 90; break;
			case 32: desiredClawAngle = 90; break;
			case 33: desiredLiftAngle = 0; desiredMovementAmount = 180; desiredMovementDirection = -1; break;
			case 34: desiredRotationAngle = -270; break;
			case 35: desiredMovementAmount = 90; desiredMovementDirection = 1; break;
			case 36: desiredRotationAngle = -360; desiredClawAngle = 0; break;
			case 37: desiredMovementAmount = 180; desiredMovementDirection = 1; desiredLiftAngle = 90; break;
			case 38: desiredClawAngle = 90; break;
			case 39: desiredLiftAngle = 0; desiredMovementAmount = 180; desiredMovementDirection = -1; break;
			case 40: desiredRotationAngle = -270; break;
			case 41: desiredMovementAmount = 90; desiredMovementDirection = 1; break;
			case 42: desiredClawAngle = 0; desiredRotationAngle = -360; break;
			case 43: desiredMovementAmount = 180; desiredMovementDirection = 1; desiredLiftAngle = 90; break;
			case 44: desiredClawAngle = 90; break;
			default:defaultCase = true;
		}
		if(defaultCase) {
			break;
		}

		while(true) {
			if(abs(currentLiftAngle - desiredLiftAngle) > 5) {
				/* Get direction */
				int x = desiredLiftAngle - currentLiftAngle;
				x /= abs(x);
				motor[port2] = x * 127;
				motor[port3] = x * 127;
				motor[port8] = x * 127;
				motor[port9] = x * 127;
			}
			else {
				motor[port2] = 0;
				motor[port3] = 0;
				motor[port8] = 0;
				motor[port9] = 0;
			}

			nMotorEncoder[left] = 0;
			nMotorEncoder[right] = 0;

			if(currentClawAngle == 90 && abs(currentClawAngle - desiredClawAngle) > 5) {
				motor[port5] = 127;
				motor[port6] = 127;
			}
			else if(currentClawAngle == 0) {
				motor[port5] = -127;
				motor[port6] = -127;
			}

		 	nMotorEncoder[left2] = desiredMovementAmount;
		 	nMotorEncoder[right2] = desiredMovementAmount;

		 	if(deisredMovementAmount != 0) {
		 		motor[left] = 127 * desiredMovementDirection;
		 		motor[left2] = 127 * desiredMovementDirection;
		 		motor[right] = 127 * desiredMovementDirection;
		 		motor[right2] = 127 * desiredMovementDirection;
		 	}

		 	currentRotationAngle = nMotorEncoder[left2] / R;
		}
		currentLevel++;
	}
}
